<a href="https://colab.research.google.com/github/furysmuflihah/uas/blob/main/furi_siti_muflihah_I_2310642_Tugas_pertemuan%C2%A02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

berikan hasil akurasi berdasarkan jumlah data testing: <br>
1. 15% dari rata
2. 25.5% dari rata
3. 31.25% dari rata

#15% dari rata

In [6]:
#Fload data
from sklearn.datasets import load_iris
iris_datasets = load_iris()

In [7]:
print("jenis isian dataset iris = \n {}" .format(iris_datasets.keys()))


jenis isian dataset iris = 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [8]:
print("target name = {}" .format(iris_datasets['target_names']))

target name = ['setosa' 'versicolor' 'virginica']


In [9]:
print("target name = {}" .format(iris_datasets['target']))
len(iris_datasets['target'])

target name = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


150

In [10]:
("target name = {}" .format(iris_datasets['feature_names']))

"target name = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']"

In [11]:
print("data module = {}" .format(iris_datasets['data']))
print("ukuran data = {}" .format(iris_datasets['data'].shape))

data module = [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5

In [12]:
from sklearn.model_selection import train_test_split
data = iris_datasets['data'] #x
target = iris_datasets['target'] #y
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.15, random_state=0)

In [13]:
print("jumlah data x training = ", x_train.shape)
print("jumlah data x testing = ", x_test.shape)
print("jumlah data y training = ", y_train.shape)
print("jumlah data y testing = ", y_test.shape)

jumlah data x training =  (127, 4)
jumlah data x testing =  (23, 4)
jumlah data y training =  (127,)
jumlah data y testing =  (23,)


In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [15]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [16]:
import numpy as np
x_new = np.array([[3, 5.1, 5, 4.2]])
prediksi = knn.predict(x_new)
print(" hasil prediksi KNN = ", prediksi)

 hasil prediksi KNN =  [2]


In [17]:
x_test

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2]])

In [18]:
prediksi1 = knn.predict(x_test)
print("hasil prediksi KNN = ", prediksi1)

hasil prediksi KNN =  [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0]


In [19]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0])

In [20]:
print("hasil akurasi = ", knn.score(x_test, y_test))

hasil akurasi =  1.0


In [21]:
from sklearn.metrics import accuracy_score
print("hasil akurasi = ", accuracy_score(y_test, prediksi1)* 100)

hasil akurasi =  100.0


#25.5% dari rata

In [24]:
from sklearn.model_selection import train_test_split
data = iris_datasets['data'] #x
target = iris_datasets['target'] #y
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.255, random_state=0)

In [25]:
print("jumlah data x training = ", x_train.shape)
print("jumlah data x testing = ", x_test.shape)
print("jumlah data y training = ", y_train.shape)
print("jumlah data y testing = ", y_test.shape)

jumlah data x training =  (111, 4)
jumlah data x testing =  (39, 4)
jumlah data y training =  (111,)
jumlah data y testing =  (39,)


In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [27]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [28]:
import numpy as np
x_new = np.array([[3, 5.1, 5, 4.2]])
prediksi = knn.predict(x_new)
print(" hasil prediksi KNN = ", prediksi)

 hasil prediksi KNN =  [2]


In [29]:
x_test

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2

In [30]:
prediksi1 = knn.predict(x_test)
print("hasil prediksi KNN = ", prediksi1)

hasil prediksi KNN =  [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1]


In [31]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1])

In [32]:
print("hasil akurasi = ", knn.score(x_test, y_test))

hasil akurasi =  0.9743589743589743


In [33]:
from sklearn.metrics import accuracy_score
print("hasil akurasi = ", accuracy_score(y_test, prediksi1)* 100)

hasil akurasi =  97.43589743589743


#31.25% dari rata

In [36]:
from sklearn.model_selection import train_test_split
data = iris_datasets['data'] #x
target = iris_datasets['target'] #y
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.3125, random_state=0)

In [37]:
print("jumlah data x training = ", x_train.shape)
print("jumlah data x testing = ", x_test.shape)
print("jumlah data y training = ", y_train.shape)
print("jumlah data y testing = ", y_test.shape)

jumlah data x training =  (103, 4)
jumlah data x testing =  (47, 4)
jumlah data y training =  (103,)
jumlah data y testing =  (47,)


In [39]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [40]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [41]:
import numpy as np
x_new = np.array([[3, 5.1, 5, 4.2]])
prediksi = knn.predict(x_new)
print(" hasil prediksi KNN = ", prediksi)

 hasil prediksi KNN =  [2]


In [42]:
x_test

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2

In [43]:
prediksi1 = knn.predict(x_test)
print("hasil prediksi KNN = ", prediksi1)

hasil prediksi KNN =  [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0 1 2]


In [44]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2])

In [45]:
print("hasil akurasi = ", knn.score(x_test, y_test))

hasil akurasi =  0.9787234042553191


In [46]:
from sklearn.metrics import accuracy_score
print("hasil akurasi = ", accuracy_score(y_test, prediksi1)* 100)

hasil akurasi =  97.87234042553192


#